global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "unifi_poller"
    static_configs:
      - targets: ["unpoller:9130"]

  - job_name: "node_exporter"
    file_sd_configs:
      - files:
        - "/etc/prometheus/targets/linux_targets.yml"
    relabel_configs:
      - target_label: group
        replacement: linux_servers

